const express = require("express");
const router = express.Router();
const validator = require('validator');
const upload = require('../middleware/uploadMiddlware');
const User = require("../models/user"); // ensure correct path

// Get user by ID
router.get("/:id", async (req, res) => {
  try {
    const user = await User.findById(req.params.id).populate("bookings"); // bookings field agar hai
    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    res.json(user); // ya { bookings: user.bookings } agar sirf bookings chahiye
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Error fetching user data" });
  }
});

// Update user details
router.put("/:id", upload.single("picture"), async (req, res) => {
  try {
    const { name, email } = req.body;

    if (email && !validator.isEmail(email)) {
      return res.status(400).json({ message: 'Invalid email format' });
    }

    if (name && !validator.isLength(name, { min: 2, max: 60 })) {
      return res.status(400).json({ message: 'Name must be 2-60 characters long' });
    }
    const user = await User.findById(req.params.id);

    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    user.name = name || user.name;
    user.email = email || user.email;

    // Agar picture bheji hai
    if (req.file) {
      // Store filename generated by multer disk storage; in production consider Cloudinary/S3
      user.picture = `/uploads/${req.file.filename}`;
    }

    await user.save();

    res.json({ user });
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Error updating user profile" });
  }
});

module.exports = router;